version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  login_service:
    build:
      context: ./login_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  register_service:
    build:
      context: ./register_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  
  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"